---
- name: Install Apache Tomcat  Server1
  hosts: 10.252.134.151
  
  tasks:
  - name: Install Java
    yum:
      name: java
      state: latest
  - name: Download Apache Tomcat Server Package
    get_url:
      url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.58/bin/apache-tomcat-8.5.58.tar.gz
      dest: /opt
  - name: Extracting the  Apache Tomcat Server Tar File.
    unarchive:
      src: /opt/apache-tomcat-8.5.58.tar.gz
      dest: /opt
      remote_src: yes
  - name: Downloading the The Jenkins.war file
    get_url:
      url: https://get.jenkins.io/war-stable/2.249.1/jenkins.war
      dest: /opt/apache-tomcat-8.5.58/webapps
      
  - name: Downloading the war from nexus from repo
    get_url:
      url: 	http://10.252.134.147:8081/repository/warDeploy/com/jdevs/Cloud-DevOps_1/1.0-SNAPSHOT/Cloud-DevOps_1-1.0-20201105.233002-1.war
      dest: /opt/apache-tomcat-8.5.58/webapps
      
  - name: Starting the Apache Tomcat Server Software
    shell: nohup /opt/apache-tomcat-8.5.58/bin/startup.sh

